/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "个人日记",
  "description": "Adroi",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Hello VuePress",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-64996c2f",
      "path": "/"
    },
    {
      "title": "Hello VuePress11111",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-27c17142",
      "path": "/guide/"
    },
    {
      "title": "qweqweqwe",
      "frontmatter": {},
      "regularPath": "/guide/a.html",
      "relativePath": "guide/a.md",
      "key": "v-9c030202",
      "path": "/guide/a.html"
    }
  ],
  "themeConfig": {
    "sidebar": [
      {
        "title": "Group 1",
        "collapsable": true,
        "children": [
          "/guide/",
          "/guide/a"
        ]
      },
      {
        "title": "Group 2",
        "children": []
      }
    ],
    "sidebarDepth": 2
  }
}